### ISSUE TITLE
Setup Page

### ISSUE THREAD

**Issue by nlhkabu** [novafloss/formidable-ui#71]
Any new design will need to account for the current design of the (Django based) setup page:

![capture_du_2015-11-23_17-50-05_1024](https://cloud.githubusercontent.com/assets/3323703/11345209/72c17110-920d-11e5-8d12-3c573bfef355.png)

Or alternatively, if a new design is developed, then it will need to be applied to this page too.

**Comment by egouy** [comment]
@nlhkabu your thoughts on the design? :)
@leotrouvtou do you know why the Description field is currently mandatory and where it is used?

**Comment by leotrouvtou** [comment]
The description is used for the search  :  you can put metadata inside the descritption and search for it

**Comment by benjamincadars** [comment]
@egouy let's keep the description field mandatory

**Comment by egouy** [comment]
Updated in consequence https://github.com/peopledoc/formidable-ui/issues/71#issuecomment-220679791

**Comment by egouy** [comment]
In Processes and Process Templates, any Basic or Custom Forms are available (depending of the Display settings):

**Process > Fill a Form**
**Process Templates > Fill a Form**

![peopleask - create a task - google chrome 2016-05-25 17 15 47](https://cloud.githubusercontent.com/assets/4729996/15545584/2e77266e-229d-11e6-9394-52da6b45c7b9.png)

**Process Templates > PDF Templates**

![peopleask - creating a pdf template - google chrome 2016-05-25 17 13 45](https://cloud.githubusercontent.com/assets/4729996/15545585/2e7a177a-229d-11e6-8138-636ccdfc98d5.png)

**Comment by nlhkabu** [comment]
My 2c:

'basic' and 'custom' dropdown > great idea.  I much prefer this wording.  Ignore my earlier comments on 'standard template' and 'custom built'.

:+1: The mockups look good. 

I think we could improve the employee confirmation message:
"Write a message to show to the employee when they successfully fill out the form."

**Comment by benjamincadars** [comment]
>"Write a message to show to the employee when they successfully fill out the form."
:+1:

**Comment by benjamincadars** [comment]
ping @GreatWizard for review!
This is the discussion about the integration of the form builder inside the existing interface.

**Comment by GreatWizard** [comment]
I like the ideas around the setup page!
The wizard on this page is not a real wizard. We will have to keep how it works currently and save the metadata of the form before going into the JS form builder.
The next button will a "Save and go to the builder" button.

**Comment by benjamincadars** [comment]
@nlhkabu can you provide a final mockup taking into account all that we said in this thread and then update your initial ticket ?
@GreatWizard when do you need that for ?

**Comment by nlhkabu** [comment]
Sure @benjamincadars :)
When do you need this by?

**Comment by benjamincadars** [comment]
@GreatWizard tell us!

**Comment by GreatWizard** [comment]
For the next week it will be fine. Thanks :)

**Comment by benjamincadars** [comment]
Up

**Comment by nlhkabu** [comment]
Questions on this ticket:

@egouy suggested that we want to be able to display basic forms in tasks - is this something we actually want to do?

If yes, what settings might be associated with this new feature?  Currently the mockup has all of the secondary settings nested under a 'Request settings' title https://github.com/novafloss/formidable-ui/issues/71#issuecomment-220679791

Would we need to add another section for 'Tasks Settings'?

**Comment by nlhkabu** [comment]
In fact, the same question also stands for custom forms - are there any settings for tasks that we need to account for?

**Comment by benjamincadars** [comment]
I think it's better if basic forms are also available for tasks but it's not low priority compared to migrating old forms into formdiable

**Comment by nlhkabu** [comment]
I couldn't find the mockups that @egouy made on Balsamiq, so I had to remake them.  I have made some changes so that the interface is more consistent with the layouts we are developing with volzord.

![setup forms basic and custom](https://cloud.githubusercontent.com/assets/3323703/17367148/c6e777c6-5986-11e6-9abb-56fd6b97bfd2.png)

https://peopledoc.mybalsamiq.com/mockups/4820940.png?key=7f390f938b4e93569f2f82b49985d15fb5e1de9c

**Comment by GreatWizard** [comment]
Create this into ask specs
